### ISSUE TITLE
readyState is open after closing connection

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#14]
The `WebSocket.readyState` is still open after closing the connection:

```js
const server = new WS('ws://localhost:8080');
const connection = await server.connected;

server.close();

await server.closed;

// outputs true
console.log(connection.readyState === WebSocket.OPEN); 
```

**Comment by romgain** [comment]
Hi @marcospassos !

This is an issue with [mock-socket](https://github.com/thoov/mock-socket), the library we use for mocking out websocket connections.

(I _think_ that this issue is due to a typo here: https://github.com/thoov/mock-socket/blob/master/src/server.js#L104 - this should probably say `WebSocket.CLOSED` instead of `WebSocket.CLOSE`)

Would you mind opening this on mock-socket's bug tracker?

If this is super important for you, I guess we could work around this issue here (PRs welcome!). But I obviously would prefer to wait for an upstream fix.

**Comment by marcospassos** [comment]
Done: https://github.com/thoov/mock-socket/issues/267
