### ISSUE TITLE
WS class "on" method callback says it returns type Server when it should be WebSocket

### ISSUE THREAD

**Issue by DBosley** [romgain/jest-websocket-mock#26]
The type on this line seems to be incorrect. When inspecting the object in a debugger, it's a WebSocket, not a server.

https://github.com/romgain/jest-websocket-mock/blob/4ae9365c1974465ac9bdfe63002a6d9a4ce75fad/src/websocket.ts#L57

**Comment by DBosley** [comment]
Something is odd with the method call here:

https://github.com/romgain/jest-websocket-mock/blob/4ae9365c1974465ac9bdfe63002a6d9a4ce75fad/src/__tests__/websocket.test.ts#L145

`socket.close()`'s signature is `close(code?: number, reason?: string)` (and code has to either be 1000 or between 3000 and 4999).

I've tried changing the test to be `socket.close(3003, "NOPE")` but the event recieved in the `onClose` method always has the code as `1000`. The test functions properly if you hand it a `CloseOptions` object, but typescript says that's invalid.

**Comment by DBosley** [comment]
I just noticed #25, Apparently this issue is with mock-socket?

The reason I made this issue is because I'm trying to do something like this:

```
const server = new WS('ws://localhost:1234');
server.on('connection', (socket) => {
  socket.on('message', () => {
    socket.send(createBadTokenError()); // this is a custom Protobuf authentication error
  });
);
const client = new WebSocket('ws://localhost:1234');
client.once('error', (err) => {
  expect(err).toBeDefined();
});
```

I can't figure out how to accomplish this with jest-websocket-mock if the callback for `server.on('connected'` is a server and not a socket.

**Comment by romgain** [comment]
Hi @DBosley !

Thanks for raising this!

I had another look, and I found the issue. The `WebSocket` returned by the "connection" callback is actually passed through a Proxy that changes its behaviour (and the signature of the `close` method): https://github.com/thoov/mock-socket/blob/master/src/helpers/proxy-factory.js#L9


Until this is fixed properly in mock-socket, the solution would be for us to define a new `MockWebSocket` interface that extends `WebSocket`, but overrides the signature of the `close` method.

I'd be happy to merge a PR if you want to make this change, otherwise I'll try to fix it tomorrow 🙂 


Thanks!

**Comment by DBosley** [comment]
Thanks @romgain,

I found another problem with `mock-socket` that essentially makes it impossible for us to use: The WebSocket type they mock doesn't actually implement all the methods WebSocket from `'ws'` implements. Namely EventEmitter methods like `once()`. I have to open an issue on their library to report this, but it means I can't use your library or `mock-socket` for my project.

**Comment by romgain** [comment]
Oh, that's a shame, I didn't realise that `ws` wasn't 100% compatible with browsers' `WebSocket`...

I'll clarify this in the docs.
