### ISSUE TITLE
Example from Docs doesn't work

### ISSUE THREAD

**Issue by nshaikhinurov** [romgain/jest-websocket-mock#3]
@romgain huge thank you for such a great idea of a package for convinient testing websockets 👍 I've just fell in love with it while reading the docs 😍

But unfortunately it seems that an example from the doc doesn't work for me:

```js
import WebSocket from 'ws'
import JestWebsocketMock from 'jest-websocket-mock'

test("the server keeps track of received messages, and yields them as they come in", async () => {
  const server = new JestWebsocketMock("ws://localhost:1234");
  const client = new WebSocket("ws://localhost:1234");

  await server.connected;
  client.send("hello");
  await expect(server).toReceiveMessage("hello");
  expect(server).toHaveReceivedMessages(["hello"]);
});
```

Jest fails with this message:
connect ECONNREFUSED 127.0.0.1:1234

I suppose my `client` instanse can't manage to connect to `server` mock. 

Please, could you help me to solve this issue?

Thanks again for a good project

**Comment by nshaikhinurov** [comment]
By the way my ws client is Node (not the browser) and I'm importing WebSocket from 'ws' package.
However using a WebSocket from Mock Socket like below
```js
import { WebSocket } from 'mock-socket'
```
made the test pass somehow. I think there may be an issue with using WebSocket from 'ws' package

**Comment by nshaikhinurov** [comment]
Ok, that was fun for me to realise i was sending real requests via 'ws' package to a mocked server which can't handle them by design 😂

**Comment by romgain** [comment]
Hi @nshaikhinurov ! Thanks for the report!

Your use case is perfectly valid - you should definitely be able to send requests to the mock server.

You're seeing an issue because `mock-socket` only mocks out the global `WebSocket` object. If you need to mock out the `WebSocket` from the `ws` package, you'll have to set up a [manual mock](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules):

* Create a `__mocks__` folder in your project's root directory
* Add a `__mocks__/ws.js` file:
```js
// __mocks__/ws.js
export { WebSocket as default } from "mock-socket";
```

That will instruct Jest to use `mock-socket`'s implementation instead of the "real" `ws` one in tests.

I'll add a section in the docs and I'll see if I can make this a bit friendlier as well.

**Comment by r1b** [comment]
I use ws like this:

```js
import WebSocket from 'ws';
// connect
new WebSocket(...)
// listen
new WebSocket.Server(...)
```

So I also had to put the Server on the WebSocket export, so my ws.js looked like:

```js
import { WebSocket, Server } from "mock-socket";

WebSocket.Server = Server;

export default WebSocket;
```

Unfortunately I had more issues after that.. `mock-socket` does not appear to implement the EventEmitter interface (`on`, etc) - so AFAICT `mock-socket` is not usable from node. Did this ever work?
