### ISSUE TITLE
Make Timeout in toReceiveMessage configurable

### ISSUE THREAD

**Issue by svh2811** [romgain/jest-websocket-mock#32]

**Comment by romgain** [comment]
Hi @svh2811 !

Simiarly to #31, would you mind giving some examples of what you are trying to test?


When testing timeouts, it's usually better to mock timers rather than artificially introduce delays, as they can make tests slow and flakey.

(For instance, jest will kill tests if they take longer than 5 seconds - which makes it impossible to test longer timeout logics without mocking out the timers.)

**Comment by svh2811** [comment]
Agreed, it's better to use mocking timer, but unfortunately to achieve this, we need to do some serious code refactoring. Hence a configurable timeout in ReceiveMessage would have immediately helped us. Also, jest timeouts can be configured.

**Comment by romgain** [comment]
Hi @svh2811 !

I think that's reasonable. Would you be open to sending a PR that adds a `setWebsocketTime` function that mutates the `WAIT_DELAY` variable in `matchers.ts`?
